image:
  repository: "ghcr.io/arfnds/personal-site"
  tag: "v1.6.0"
imagePullSecrets:
  - "ghcr.io"
containerPort: 3000
container:
  imagePullPolicy: Always
probe:
  enabled: false
vars:
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://obs.arbrerus.ru/api/default/"
ingress:
  host: "arnaudfernandes.com"
  tlsEnabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spreadAcrossNodes: false
nodeSelector:
  topology.kubernetes.io/region: "europe-central-1"
resources:
  ignore: true
