name: Deploy to PROD

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Docker image tag to deploy'
        required: true
        type: string

jobs:
  update-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update image tag in values.yaml
        run: |
          # Install yq
          wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
          
          # Update the image.tag value in values.yaml
          yq -i '.image.tag = "${{ github.event.inputs.imageTag }}"' charts/values.yaml
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add charts/values.yaml
          git commit -m "chore: update image tag to ${{ github.event.inputs.imageTag }}"
          git push